
export const cards = [
  {
    id: 1,
    title: "Male",
    desc: "Male Designs",
    img: '../public/img/male.JPG',
  },
  {
    id: 2,
    title: "Female",
    desc: "Female Designs",
    img: '../public/img/female.png',
  },
  {
    id: 3,
    title: "Kids",
    desc: "Kids Designs",
    img: '../public/img/kids.JPG',
  },
  {
    id: 4,
    title: "Tailor",
    desc: "Shape Your Clothe",
    img: '../public/img/tailor.JPG',
  },

];

export const projects = [
  {
    id: 1,
    img: "https://images.pexels.com/photos/1462935/pexels-photo-1462935.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Web and Mobile Design",
    username: "Anna Bell",
  },
  {
    id: 2,
    img: "https://images.pexels.com/photos/270408/pexels-photo-270408.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Logo Design",
    username: "Morton Green",
  },
  {
    id: 3,
    img: "https://images.pexels.com/photos/4144923/pexels-photo-4144923.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Animated GIFs",
    username: "Emmett Potter",
  },
  {
    id: 4,
    img: "https://images.pexels.com/photos/4348404/pexels-photo-4348404.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Packaging Design",
    username: "Freddie Johnston",
  },
  {
    id: 5,
    img: "https://images.pexels.com/photos/4458554/pexels-photo-4458554.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Social Media Design",
    username: "Audrey Richards",
  },
  {
    id: 6,
    img: "https://images.pexels.com/photos/4465831/pexels-photo-4465831.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1036627/pexels-photo-1036627.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Illustration",
    username: "Dalton Hudson",
  },
  {
    id: 7,
    img: "https://images.pexels.com/photos/6077368/pexels-photo-6077368.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1858175/pexels-photo-1858175.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Book Design",
    username: "Hannah Dougherty",
  },
  {
    id: 8,
    img: "https://images.pexels.com/photos/4065876/pexels-photo-4065876.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1680175/pexels-photo-1680175.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Digital Marketing",
    username: "Ward Brewer",
  },
];

export const gigs = [
  {
    id: 1,
    img:'../public/img/1.JPG',
    pp: '../public/img/2.JPG',
    desc: "I will create designer clothes",
    price: 590,
    star: 5,
    username: "Anna Bell",
  },
  {
    id: 2,
    img: '../public/img/7.webp',
    pp: '../public/img/8.webp',
    desc: "I will create designer clothes",
    price: 790,
    star: 5,
    username: "Lannie Coleman",
  },
  {
    id: 3,
    img: '../public/img/3.JPG',
    pp: '../public/img/4.webp',
    desc: "I will create designer clothes",
    price: 1120,
    star: 5,
    username: "Carol Steve",
  },
  {
    id: 4,
    img:'../public/img/5.JPG',
    pp: '../public/img/5.JPG',
    desc: "I will create designer clothes",
    price: 990,
    star: 4,
    username: "Don Weber",
  },
  {
    id: 5,
    img:'../public/img/10.webp',
    pp: '../public/img/10.webp',
    desc: "I will create designer clothes",
    price: 590,
    star: 5,
    username: "Audrey Richards",
  },
  {
    id: 6,
    img: '../public/img/4.webp',
    pp: '../public/img/4.webp',
    desc: "I will create designer clothes",
    price: 790,
    star: 4,
    username: "Walton Shepard ",
  },
  {
    id: 7,
    img: '../public/img/8.webp',
    pp: '../public/img/8.webp',
    desc: "I will create designer clothes",
    price: 890,
    star: 5,
    username: "Waverly Schaefer",
  },
  {
    id: 8,
    img: '../public/img/6.jpg',
    pp: '../public/img/6.jpg',
    desc: "I will create designer clothes",
    price: 1100,
    star: 4,
    username: "Wilton Hunt",
  },{
    id: 1,
    img:'../public/img/1.JPG',
    pp: '../public/img/2.JPG',
    desc: "I will create designer clothes",
    price: 590,
    star: 5,
    username: "Anna Bell",
  },
  {
    id: 2,
    img: '../public/img/7.webp',
    pp: '../public/img/8.webp',
    desc: "I will create designer clothes",
    price: 790,
    star: 5,
    username: "Lannie Coleman",
  },
  {
    id: 3,
    img: '../public/img/3.JPG',
    pp: '../public/img/4.webp',
    desc: "I will create designer clothes",
    price: 1120,
    star: 5,
    username: "Carol Steve",
  },
  {
    id: 4,
    img:'../public/img/5.JPG',
    pp: '../public/img/5.JPG',
    desc: "I will create designer clothes",
    price: 990,
    star: 4,
    username: "Don Weber",
  },
  {
    id: 5,
    img:'../public/img/10.webp',
    pp: '../public/img/10.webp',
    desc: "I will create designer clothes",
    price: 590,
    star: 5,
    username: "Audrey Richards",
  },
  {
    id: 6,
    img: '../public/img/4.webp',
    pp: '../public/img/4.webp',
    desc: "I will create designer clothes",
    price: 790,
    star: 4,
    username: "Walton Shepard ",
  },
  {
    id: 7,
    img: '../public/img/8.webp',
    pp: '../public/img/8.webp',
    desc: "I will create designer clothes",
    price: 890,
    star: 5,
    username: "Waverly Schaefer",
  },
  {
    id: 8,
    img: '../public/img/6.jpg',
    pp: '../public/img/6.jpg',
    desc: "I will create designer clothes",
    price: 1100,
    star: 4,
    username: "Wilton Hunt",
  },

];
